# Generated by Django 4.0.6 on 2022-07-25 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Midia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.TextField(max_length=300)),
                ('titulo', models.CharField(max_length=150)),
                ('planta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pjgplantas.planta')),
            ],
        ),
        migrations.DeleteModel(
            name='Curtida',
        ),
    ]
