# Generated by Django 4.0.6 on 2022-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pjgplantas', '0003_remove_midia_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='midia',
            name='local',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
